<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>formulario de captura de numeros</title>
</head>
<body>
    

<h1> PROMEDIO DE TIEMPO RECORRIDO </h1>
<H2>FORMULARIO DE CAPTURA</H2>
<form action=""></form>
<form action="02_ejercicio.php" method="get">
<label>Digite el tiempo del dia lunes:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
<input type="number" name="lunes"><p>
<label>Digite el tiempo del dia martes:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </label>
<input type="number" name="martes"><p>
<label>Digite el tiempo del dia miercoles:&nbsp;&nbsp;&nbsp;&nbsp;</label>
<input type="number" name="miercoles"><p>
<input type="submit" name="btn_enviar" value="EJECUTAR">





</form>


<br>




</body>
</html>
<?php

    
    echo '<a href="http://localhost/ADSI2338368%20DAYANA_EINER/MENU.php"><input type="submit" name="btn_MENU" value="MENU"></a>';

?>